### Stream Request
POST http://localhost:7860/stream
Content-Type: application/json
Authorization: Bearer no-key

{
    "messages": ["How does leaf curl virus transmit"]
}

### RAG Request
POST https://dlsathvik04-lcvd-language.hf.space/rag/direct
Content-Type: application/json
Authorization: Bearer no-key

{
    "class_name" : "chilli-leaf_curl_virus",
    "history": [],
    "prompt" : "what is this virus? and how can it be cured?"
}
